//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBonusSMEntities1 : DbContext
    {
        public DBBonusSMEntities1()
            : base("name=DBBonusSMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblFenomenler> TblFenomenler { get; set; }
        public virtual DbSet<TblPaketler> TblPaketler { get; set; }
        public virtual DbSet<TblSayfalar> TblSayfalar { get; set; }
        public virtual DbSet<TblUyeler> TblUyeler { get; set; }
        public virtual DbSet<TblCekilisler> TblCekilisler { get; set; }
        public virtual DbSet<TblTalepler> TblTalepler { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblBankalar> TblBankalar { get; set; }
        public virtual DbSet<TblMetaEtiketleri> TblMetaEtiketleri { get; set; }
        public virtual DbSet<TblYorumlar> TblYorumlar { get; set; }
        public virtual DbSet<TblPaketKategoriler> TblPaketKategoriler { get; set; }
        public virtual DbSet<TblYaziKategori> TblYaziKategori { get; set; }
        public virtual DbSet<TblYazilar> TblYazilar { get; set; }
        public virtual DbSet<TblYaziYorumlar> TblYaziYorumlar { get; set; }

        public System.Data.Entity.DbSet<SponsorBulmaSitesi.Models.YaziModel> YaziModels { get; set; }
    }
}
