//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBankalar
    {
        public int Id { get; set; }
        public string BankaAdi { get; set; }
        public string IbanNo { get; set; }
        public string HesapNo { get; set; }
        public string Isim { get; set; }
        public string BankaLogo { get; set; }
    }
}
