//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCekilisler
    {
        public int Id { get; set; }
        public string CekilisLinki { get; set; }
        public Nullable<System.DateTime> CekilisTarihi { get; set; }
        public string CekilisDurumu { get; set; }
        public Nullable<System.DateTime> CekilisBitisTarihi { get; set; }
        public string ToplamOdul { get; set; }
    }
}
