//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFenomenler
    {
        public int Id { get; set; }
        public string FenomenAdi { get; set; }
        public string TakipciSayisi { get; set; }
        public string TakipciKapasite { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string InstaUrl { get; set; }
        public string Foto { get; set; }
    }
}
