//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPaketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPaketler()
        {
            this.TblTalepler = new HashSet<TblTalepler>();
        }
    
        public int Id { get; set; }
        public string PaketAdi { get; set; }
        public string PaketAciklama { get; set; }
        public string KTakipciSayisi { get; set; }
        public Nullable<decimal> Fiyati { get; set; }
        public string Aktif { get; set; }
        public string PaketSeoUrl { get; set; }
        public Nullable<int> Kategori { get; set; }
        public string TeslimSuresi { get; set; }
        public string PaylasacakSayfalar { get; set; }
        public Nullable<System.DateTime> CekilisTarihi { get; set; }
        public string OdemeLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTalepler> TblTalepler { get; set; }
        public virtual TblPaketKategoriler TblPaketKategoriler { get; set; }
    }
}
