//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSayfalar
    {
        public int Id { get; set; }
        public Nullable<int> Uye { get; set; }
        public string SayfaAdi { get; set; }
    
        public virtual TblUyeler TblUyeler { get; set; }
    }
}
