//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTalepler
    {
        public int Id { get; set; }
        public string TalepKodu { get; set; }
        public Nullable<int> Paket { get; set; }
        public string Adi { get; set; }
        public string Telefon { get; set; }
        public string TalepCinsiyet { get; set; }
        public string TalepYas { get; set; }
        public string TalepAciklama { get; set; }
        public string TalepDurum { get; set; }
        public string TalepOdeme { get; set; }
        public string SayfaAdi { get; set; }
        public string ProfilLink { get; set; }
        public Nullable<System.DateTime> TalepTarih { get; set; }
        public string CekilisLink { get; set; }
        public string Email { get; set; }
        public string DekontDurumu { get; set; }
        public string DekontFoto { get; set; }
        public string WhatsapGrubu { get; set; }
        public string OdemeSekli { get; set; }
    
        public virtual TblPaketler TblPaketler { get; set; }
    }
}
