//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYaziYorumlar
    {
        public int Id { get; set; }
        public Nullable<int> Yazi { get; set; }
        public string Yorum { get; set; }
        public string YorumAdi { get; set; }
        public string YorumDurum { get; set; }
        public string YorumMail { get; set; }
    
        public virtual TblYazilar TblYazilar { get; set; }
    }
}
