//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYazilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblYazilar()
        {
            this.TblYaziYorumlar = new HashSet<TblYaziYorumlar>();
        }
    
        public int Id { get; set; }
        public string YaziBaslik { get; set; }
        public string YaziMetin { get; set; }
        public Nullable<System.DateTime> YaziTarih { get; set; }
        public string YaziDurum { get; set; }
        public string YaziSeoUrl { get; set; }
        public Nullable<int> YaziKategori { get; set; }
    
        public virtual TblYaziKategori TblYaziKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblYaziYorumlar> TblYaziYorumlar { get; set; }
    }
}
