//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SponsorBulmaSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblYorumlar
    {
        public int Id { get; set; }
        public string YorumAdi { get; set; }
        public string Yorum { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string YorumMail { get; set; }
        public string YorumOnay { get; set; }
    }
}
